language: node_js
node_js:
  - 10
services:
  - mysql
  - redis-server
before_install:
  - mysql -e 'CREATE DATABASE eventdaemon;'
install:
  -  npm install
jobs:
  include:
    - stage: "Validate & tests"
      name: "ESLint"
      script:
        - npm run lint 
    - name: "Tests"
      script:
        - npm test
        - npm run coverage
    - stage: Deploy
      name: "Deploy docs to GH pages"
      script:
        - npm run docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        on:
          branch: master
        local-dir: out/